name: flutter_font_picker
description: A Flutter widget that lets the user select a Google Font from a custom dropdown/screen.
version: 1.2.0
homepage: https://github.com/whiplashoo/flutter_font_picker

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.3
  shared_preferences: ^2.0.3

dev_dependencies:
  flutter_lints: ^2.0.1
  dart_code_metrics: ^4.15.2
  flutter_test:
    sdk: flutter
  args: ^2.4.0
  
flutter:


